// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TrainingSystem.Data.migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230317124757_fixFKCascade")]
    partial class fixFKCascade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ComapnyId");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("92f04823-3b8f-48c4-a37f-32529f8724f5"),
                            Adress = "any adress at Cairo",
                            Country = "Egypt",
                            Name = "Nasa"
                        },
                        new
                        {
                            Id = new Guid("455cdf8b-9469-45e4-aa05-0c24b3541503"),
                            Adress = "any adress at Maiami",
                            Country = "USA",
                            Name = "Tesla"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid?>("CompanyOfTheEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyOfTheEmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67adda78-4608-42e7-9463-3773e0ffa4db"),
                            Age = 30,
                            Name = "Ahmed",
                            Position = "SE Engineer"
                        },
                        new
                        {
                            Id = new Guid("3e0f6702-f265-4e61-912a-66140071974c"),
                            Age = 40,
                            Name = "John",
                            Position = "DEVOPS"
                        },
                        new
                        {
                            Id = new Guid("5134eb68-3a7e-4042-a549-b92b87abbc03"),
                            Age = 50,
                            Name = "Mai",
                            Position = "Tester"
                        },
                        new
                        {
                            Id = new Guid("7c3ea679-55e9-42fe-908d-65b5823f54c0"),
                            Age = 20,
                            Name = "Sara",
                            Position = "Product Owner"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Company", "CompanyOfTheEmployee")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyOfTheEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CompanyOfTheEmployee");
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
